### ISSUE TITLE
Error while running the script line 7: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by wolli1234** [JsBergbau/CCS811-Firmware-Updater#1]
Hello,

I'm trying to run the script in the terminal via ssh on my raspberry pi. First I made it executable and then I tried:

`./ccs811Firmwareupdater.py --adress 0x5A --firmware-file CCS811_FW_App_v2-0-1.bin`

I get the following error:

```
./ccs811Firmwareupdater.py: line 7: syntax error near unexpected token `newline'
./ccs811Firmwareupdater.py: line 7: `<!DOCTYPE html>'
```

Seems to be related to the re package. Do I have to install something to import this module?
Sorry I'm not very familiar with python.

Best regards,
Wolli

**I found my problem, I did not download the raw file of the script, that was all :).**

**Comment by JsBergbau** [comment]
Hallo wolli1234,
`./ccs811Firmwareupdater.py: line 7: `<!DOCTYPE html>'` that error made me also think, that you've tried to execute a html file with python.
Glad that it works now.
